Repository MOSS2023ASE/service-frontend, pull requests merged in 2023-04, with the labels that each got.

#114 [chore](SSL):初始化devSSL证书配置
  .github/workflows/dev.yml
  nginx_dev.conf
Labels: devops

#115 [chore](SSL):尝试将http请求重定向至https
  nginx_dev.conf
Labels: devops

#116 [fix](修复3个小bug):错别字修改，去掉全屏按钮,辅导师看不到用户管理
  src/layout/components/Navbar.vue
  src/router/index.js
  src/utils/bus.js
  src/views/login/index.vue
Labels: bug

#121 [fix](http):将http引用图片的代码以https取代
  public/index.html
  src/layout/components/Navbar.vue
  src/views/login/index.vue
Labels: bug, devops

#122 将源码中http获取图片的部分以https取代
  public/index.html
  src/layout/components/Navbar.vue
  src/views/login/index.vue
Labels: bug, devops

#126 [fix](用户管理和个人主页)：去除调试的log信息
  src/views/userInfo/userInfo.vue
  src/views/userInfo/userIssue.vue
  src/views/userManage/labelManage.vue
  src/views/userManage/tutorManage.vue
  src/views/userManage/userList.vue
Labels: bug

#132 [fix](添加弹窗):添加弹窗
  src/components/Notify/TextBox.vue
  src/views/issueInfo/components/Confirm.vue
  src/views/issueInfo/components/MyRichText.vue
  src/views/issueInfo/issueInfoDetail.vue
  src/views/searchIssue/components/issueItem.vue
Labels: bug

#134 [fix](nginx):将静态文件大小上限设置为5m，解决413报错
  nginx_dev.conf
  nginx_prod.conf
Labels: bug

#135 [fix](增大timeout):timeout*10
  src/utils/request.js
Labels: bug
